-- ==============================================================================
-- NexBuy-Global: 百思买模式 3C 数码跨境电商数据库架构定义 (PostgreSQL)
-- 适用场景: 消费电子大宗/零售、SPU/SKU多规格、智能海外地址簿、多币种锁价与防超卖秒杀
-- 方言规范: PostgreSQL 14+ (兼容 Supabase / AWS RDS PostgreSQL)
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. 品牌表 (Brand)
--    用于高品质 3C 科技数码筛选 (如 Apple, Sony, Samsung, Anker, Nintendo)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS t_brand (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64) NOT NULL,               -- 品牌英文名
    logo_url    VARCHAR(255) NULL,                  -- 品牌矢量 Logo URL
    description TEXT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------------------------
-- 2. 类目树形表 (Category)
--    支持百思买标准三级类目体系 (如: 消费电子 -> 手机及配件 -> 智能手机)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS t_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT NOT NULL DEFAULT 0,          -- 0 表示根节点 (一级大类)
    name        VARCHAR(64) NOT NULL,               -- 类目名称
    level       SMALLINT NOT NULL DEFAULT 1,        -- 1:一级, 2:二级, 3:末级叶子节点
    sort_order  INT NOT NULL DEFAULT 0,             -- 排序展示权重
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cat_parent ON t_category(parent_id);

-- ------------------------------------------------------------------------------
-- 3. 商品 SPU 主表 (Standard Product Unit)
--    定义标准化商品主数据，不涉及具体颜色/容量，对应百思买一个聚合商品展示页
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS t_product (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id      BIGINT NOT NULL REFERENCES t_brand(id),
    category_id   BIGINT NOT NULL REFERENCES t_category(id),
    title         VARCHAR(255) NOT NULL,            -- 商品主标题 (如 "iPhone 16 Pro Max")
    subtitle      VARCHAR(255) NULL,                -- 卖点描述
    base_price    NUMERIC(10,2) NOT NULL,           -- 美元基准起售价 (USD)
    main_image    VARCHAR(255) NOT NULL,            -- 封面高清展示图
    detail_html   TEXT NULL,                        -- 详情富文本 / Markdown 规范
    status        SMALLINT NOT NULL DEFAULT 1,      -- 1:在售, 0:下架
    create_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_prod_category ON t_product(category_id);
CREATE INDEX IF NOT EXISTS idx_prod_brand ON t_product(brand_id);

-- ------------------------------------------------------------------------------
-- 4. 商品 SKU 规格变体表 (Stock Keeping Unit)
--    高并发库存扣减与实际交易的核心主体！包含具体颜色、容量等参数与独立库存
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS t_product_sku (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT NOT NULL REFERENCES t_product(id) ON DELETE CASCADE,
    sku_code      VARCHAR(64) NOT NULL,             -- 全局唯一 SKU 编码 (如 "IPHONE16-TITAN-256G")
    spec_data     JSONB NOT NULL,                   -- 规格键值 (如 {"color":"Desert Titanium","storage":"256GB"})
    price         NUMERIC(10,2) NOT NULL,           -- 该规格美元实际售价
    stock         INT NOT NULL DEFAULT 0,           -- 物理物理可用库存
    image_url     VARCHAR(255) NULL,                -- 该规格对应专属图片
    status        SMALLINT NOT NULL DEFAULT 1,      -- 1:启用, 0:禁用
    create_time   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sku_code UNIQUE (sku_code)
);
CREATE INDEX IF NOT EXISTS idx_sku_product ON t_product_sku(product_id);

-- ------------------------------------------------------------------------------
-- 5. 智能海外收货地址表 (User Address)
--    标准符合国际邮政规范 (支持 US / DE / JP / BR 等国税号与邮编自动校验)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS t_user_address (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL,
    recipient_name VARCHAR(64) NOT NULL,            -- 收件人全名
    phone          VARCHAR(32) NOT NULL,            -- 国际格式手机号 (带国际区号)
    country_code   VARCHAR(10) NOT NULL,            -- ISO 3166-1 alpha-2 代码 (US, DE, JP)
    state_province VARCHAR(64) NOT NULL,            -- 州 / 省 (如 California)
    city           VARCHAR(64) NOT NULL,            -- 城市 (如 San Jose)
    postal_code    VARCHAR(20) NOT NULL,            -- 国际邮政编码 (如 95112)
    street_address TEXT NOT NULL,                   -- 详细街道门牌地址
    tax_id         VARCHAR(64) NULL,                -- 跨国税号 (巴西 CPF、智利 RUT、欧盟增值税号)
    is_default     SMALLINT NOT NULL DEFAULT 0,     -- 1:默认地址, 0:否
    create_time    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_address_user ON t_user_address(user_id);

-- ------------------------------------------------------------------------------
-- 6. 国际支付流水与 3DS 认证表 (Payment Record)
--    对齐 Stripe 信用卡、Google Pay 支付中枢与 3DS 安全验证码流转
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS t_payment_record (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           BIGINT NOT NULL,             -- 关联订单 ID
    payment_channel    VARCHAR(32) NOT NULL,        -- 'STRIPE_CARD', 'GOOGLE_PAY'
    payment_intent_id  VARCHAR(128) NOT NULL,       -- Stripe 唯一交易凭单 ID
    currency           VARCHAR(10) NOT NULL,        -- 支付币种 (USD, EUR, JPY)
    amount             NUMERIC(10,2) NOT NULL,      -- 实际划扣金额
    status             SMALLINT NOT NULL DEFAULT 0, -- 0:待认证/未支付, 1:支付成功, 2:支付失败
    otp_code           VARCHAR(6) NULL,             -- 3D Secure 短信/应用授权验证申请码
    create_time        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_payment_intent UNIQUE (payment_intent_id)
);
CREATE INDEX IF NOT EXISTS idx_pay_order ON t_payment_record(order_id);

-- ------------------------------------------------------------------------------
-- 7. 跨境物流多段式追踪表 (Logistics Tracking)
--    支持真实国际海运/空运节点追踪 (顺丰国际、DHL、FedEx)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS t_logistics_track (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL,
    tracking_number VARCHAR(64) NOT NULL,           -- 国际快递运单号
    carrier         VARCHAR(32) NOT NULL,           -- 物流承运商 (DHL, FedEx, YunExpress)
    node_status     SMALLINT NOT NULL,              -- 1:保税仓打包 2:国际空运中 3:目的国海关清关 4:本地派送 5:已妥投
    node_desc       TEXT NOT NULL,                  -- 轨迹明细描述
    location        VARCHAR(64) NOT NULL,           -- 发生地点 (如 "Frankfurt Hub, DE")
    event_time      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_logistics_order ON t_logistics_track(order_id);
