-- ============================================================
-- 商城秒杀系统 —— PostgreSQL Schema
--
-- 环境一致性：本地 Docker Postgres 与线上 Supabase Postgres 方言完全相同
-- 执行时机：docker compose 首次启动时自动执行；也可手动 psql -f schema.sql
-- 幂等性：全部使用 IF NOT EXISTS，可重复执行
--
-- 与 MySQL 版本的差异（迁移要点）：
--   BIGINT AUTO_INCREMENT  -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   DATETIME               -> TIMESTAMP
--   TINYINT                -> SMALLINT
--   ON UPDATE CURRENT_TIMESTAMP -> 应用层维护（MyBatis-Plus 自动填充）
--   ENGINE=InnoDB / CHARSET    -> 不需要
--   CREATE TABLE 内联 INDEX    -> 必须拆成独立 CREATE INDEX
-- ============================================================


-- ------------------------------------------------------------
-- 1. 用户表
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS t_user (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL,
    password      VARCHAR(128) NOT NULL,                    -- BCrypt 哈希（盐已内嵌）
    created_time  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_username UNIQUE (username)
);


-- ------------------------------------------------------------
-- 2. 商品表（常规售卖）
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS goods (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(128)  NOT NULL,
    price        NUMERIC(10,2) NOT NULL,                    -- 常规售卖价
    stock        INT           NOT NULL DEFAULT 0,          -- 商品总库存
    detail       TEXT,
    create_time  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ------------------------------------------------------------
-- 3. 秒杀活动商品表
--    与 goods 解耦：同一商品可开多次秒杀，活动库存独立
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS seckill_goods (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_id       BIGINT        NOT NULL,
    seckill_price  NUMERIC(10,2) NOT NULL,
    stock_count    INT           NOT NULL DEFAULT 0,        -- 秒杀库存（Redis 未命中时的兜底真值）
    start_time     TIMESTAMP     NOT NULL,
    end_time       TIMESTAMP     NOT NULL,
    CONSTRAINT fk_seckill_goods_goods FOREIGN KEY (goods_id) REFERENCES goods (id)
);

CREATE INDEX IF NOT EXISTS idx_seckill_goods_goods_id ON seckill_goods (goods_id);
CREATE INDEX IF NOT EXISTS idx_seckill_goods_time     ON seckill_goods (start_time, end_time);


-- ------------------------------------------------------------
-- 4. 订单主表
--    id 由雪花算法生成，不做自增：批量插入后无需回查即可拿到订单号
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_info (
    id           BIGINT        PRIMARY KEY,                 -- 雪花 ID
    user_id      BIGINT        NOT NULL,
    goods_id     BIGINT        NOT NULL,
    goods_name   VARCHAR(128)  NOT NULL,                    -- 商品名快照
    order_price  NUMERIC(10,2) NOT NULL,                    -- 成交价快照
    status       SMALLINT      NOT NULL DEFAULT 0,          -- 0待支付 1已支付 2已发货 3已关闭
    create_time  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pay_time     TIMESTAMP     NULL
);

CREATE INDEX IF NOT EXISTS idx_order_user_time ON order_info (user_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_order_status    ON order_info (status, create_time);


-- ------------------------------------------------------------
-- 5. 秒杀幂等表（防重复下单）
--
--    ★ 这是"不重复下单"这条不变量的最后防线：
--      代码判断在并发下不可靠，唯一索引才是真的可靠。
--      即使 Redis 判重被绕过，这里也会拒绝第二条插入。
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS seckill_order (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT NOT NULL,
    order_id  BIGINT NOT NULL,                              -- 关联 order_info.id
    goods_id  BIGINT NOT NULL,
    CONSTRAINT uk_seckill_order_user_goods UNIQUE (user_id, goods_id)
);

CREATE INDEX IF NOT EXISTS idx_seckill_order_order_id ON seckill_order (order_id);
